site_name: My HomeLab
site_url: https://mydomain.org/mysite
theme:
  name: material
extra_javascript:
  - javascripts/mermaid-icons.js
theme:
  font:
      text: Quicksand
  name: material
  palette:
    - scheme: slate
      primary: light blue
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: light blue
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
nav:
  - Home: index.md
  - HomeLab:
    - HomeLab Layout: homelab/layout.md
  - Linux:
    - KVM: linux/kvm.md